import fs from "node:fs";
import path from "node:path";

const roots = ["content/regulations", "content/drug-development", "content/reviewer-academy"];
const output = "lib/generatedMdxContent.ts";

function walk(dir) {
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) return walk(full);
    if (entry.isFile() && entry.name.endsWith(".mdx")) return [full];
    return [];
  });
}

function parseId(file, text) {
  const match = text.match(/^id:\s*([a-zA-Z0-9_-]+)\s*$/m);
  if (match) return match[1];
  return path.basename(file, ".mdx");
}

const entries = roots.flatMap(walk).map((file) => {
  const text = fs.readFileSync(file, "utf8");
  return [parseId(file, text), text.replace(/^id:\s*[a-zA-Z0-9_-]+\s*$/m, "").trim()];
});

const body = `// This file is generated by scripts/build-content.mjs. Do not edit by hand.
export const generatedMdxContent: Record<string, string> = ${JSON.stringify(Object.fromEntries(entries), null, 2)};
`;

fs.writeFileSync(output, body);
console.log(`Generated ${output} with ${entries.length} content entries.`);
